ALTER TABLE KANDIDATUTFALL DROP COLUMN ENHETSNR;
ALTER TABLE KANDIDATUTFALL ADD COLUMN NAVKONTOR TEXT;
ALTER TABLE KANDIDATUTFALL ADD COLUMN KANDIDATLISTEID TEXT;
ALTER TABLE KANDIDATUTFALL ADD COLUMN STILLINGSID TEXT;