apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: rekrutteringsbistand-statistikk-api
  namespace: default
  labels:
    team: arbeidsgiver
spec:
  image: {{version}}
  ingresses:
    - https://arbeidsgiver.nais.preprod.local/rekrutteringsbistand-statistikk-api/
  liveness:
    path: /rekrutteringsbistand-statistikk-api/internal/isAlive
  readiness:
    path: /rekrutteringsbistand-statistikk-api/internal/isReady
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: true
  webproxy: true
