apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: rekrutteringsbistand-statistikk-api
  namespace: default
  labels:
    team: arbeidsgiver
spec:
  image: {{version}}
  ingresses:
    - https://arbeidsgiver.nais.adeo.no/rekrutteringsbistand-statistikk-api/
  liveness:
    path: /rekrutteringsbistand-statistikk-api/internal/isAlive
  readiness:
    path: /rekrutteringsbistand-statistikk-api/internal/isReady
  vault:
    enabled: true
  env:
    - name: PROFIL
      value: prod
