apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rekrutteringsbistand-statistikk-api
  namespace: toi
  labels:
    team: toi
spec:
  groups:
    - name: rekrutteringsbistand-statistikk-api
      rules:
        - alert: rekrutteringsbistand-statistikk-api
          expr: sum(up{app="rekrutteringsbistand-statistikk-api", job="nais-system/monitoring-apps-tenant"}) == 0
          for: 1s
          annotations:
            summary: Appen er nede
            action: "https://logs.adeo.no/goto/3f0b14d0-f5fb-11ec-9b1a-4723a5e7a9db"
          labels:
            namespace: toi
            severity: critical

        - alert: rekrutteringsbistand-statistikk-api
          expr: sum(increase(logd_messages_total{log_app="rekrutteringsbistand-statistikk-api",log_level="Error"}[10m])) > 0
          for: 1s
          annotations:
            summary: Appen har logget en error
            action: "https://logs.adeo.no/goto/3f0b14d0-f5fb-11ec-9b1a-4723a5e7a9db"
          labels:
            namespace: toi
            severity: critical

        - alert: rekrutteringsbistand-statistikk-api
          expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="rekrutteringsbistand-statistikk-api",log_level=~"Warning"}[3m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="rekrutteringsbistand-statistikk-api"}[3m]))) > 5
          for: 3m
          annotations:
            summary: Økning i warnings
            action: "https://logs.adeo.no/goto/3f0b14d0-f5fb-11ec-9b1a-4723a5e7a9db"
          labels:
            namespace: toi
            severity: warning

        - alert: rekrutteringsbistand-statistikk-api
          expr: (100 * (sum by (backend) (rate(traefik_backend_requests_total{code=~"^5\\d\\d", backend=~"arbeidsgiver.nais.*/rekrutteringsbistand-statistikk-api/*"}[3m])) / sum by (backend) (rate(traefik_backend_requests_total{backend=~"arbeidsgiver.nais.*/rekrutteringsbistand-statistikk-api/*"}[3m])))) > 1
          for: 3m
          annotations:
            summary: Økning i HTTP-serverfeil (5xx-responser)
            action: "https://logs.adeo.no/goto/3f0b14d0-f5fb-11ec-9b1a-4723a5e7a9db"
          labels:
            namespace: toi
            severity: warning

        - alert: rekrutteringsbistand-statistikk-api
          expr: (100 * (sum by (backend) (rate(traefik_backend_requests_total{code=~"^4\\d\\d", backend=~"arbeidsgiver.nais.*/rekrutteringsbistand-statistikk-api/*"}[3m])) / sum by (backend) (rate(traefik_backend_requests_total{backend=~"arbeidsgiver.nais.*/rekrutteringsbistand-statistikk-api/*"}[3m])))) > 1
          for: 3m
          annotations:
            summary: Økning HTTP-klientfeil (4xx-responser)
            action: "https://logs.adeo.no/goto/3f0b14d0-f5fb-11ec-9b1a-4723a5e7a9db"
          labels:
            namespace: toi
            severity: warning
