apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: rekrutteringsbistand-statistikk-api
  labels:
    team: arbeidsgiver
spec:
  receivers:
    slack:
      channel: 'inkludering-alerts-dev'
      prependText: 'rekrutteringsbistand-statistikk-api: '
  alerts:
    - alert: Applikasjonen er nede (ingen Kubernetes-pods er oppe)
      severity: danger
      expr: sum(up{app="rekrutteringsbistand-statistikk-api", job="kubernetes-pods"}) == 0
      for: 2m
      description: "App {{ $labels.app }} er nede i namespace {{ $labels.kubernetes_namespace }}"
      action: "`kubectl describe pod {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for logger"
    - alert: Sending av kandidatutfall på Kafka til Datavarehus feilet
      expr: sum(increase(rekrutteringsbistand_statistikk_kafka_feilet_total[5m])) > 0
      for: 10s
      action: "Kibana: `application: rekrutteringsbistand-statistikk-api AND cluster: dev-fss AND level: Error`"
    - alert: Økning log level ERROR
      severity: danger
      expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="rekrutteringsbistand-statistikk-api",log_level=~"Error"}[3m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="rekrutteringsbistand-statistikk-api"}[3m]))) > 1
      for: 10s
      action: "Sjekk loggene til app {{ $labels.log_app }} i namespace {{ $labels.log_namespace }}, for å se hvorfor det er så mye errors"
    - alert: Økning log level ERROR NY ALERT
      severity: danger
      expr: sum(increase(logd_messages_total{log_app="rekrutteringsbistand-statistikk-api",log_level="Error"}[5m])) > 0
      for: 10s
      action: "Sjekk loggene til app {{ $labels.log_app }} i namespace {{ $labels.log_namespace }}, for å se hvorfor det er så mye errors"
    - alert: Økning log level ERROR NY NY ALERT
      severity: danger
      expr: (sum by (log_app, log_namespace) (increase(logd_messages_total{log_app="rekrutteringsbistand-statistikk-api",log_level=~"Error"}[3m]))) > 0
      for: 10s
      action: "Sjekk loggene til app {{ $labels.log_app }} i namespace {{ $labels.log_namespace }}, for å se hvorfor det er så mye errors"
