apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rekrutteringsbistand-statistikk-api
  namespace: toi
  labels:
    team: toi
spec:
  groups:
    - name: rekrutteringsbistand-statistikk-api
      rules:
        - alert: rekrutteringsbistand-statistikk-api
          expr: kube_deployment_status_replicas_available{deployment="rekrutteringsbistand-statistikk-api"} == 0
          for: 1s
          annotations:
            summary: Appen er nede
            action: "https://logs.az.nav.no/goto/fbd44a2098fae956a0726c0c347a7632?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: critical

        - alert: rekrutteringsbistand-statistikk-api
          expr: sum(increase(log_messages_errors{app="rekrutteringsbistand-statistikk-api", level="Error"}[10m])) > 0
          for: 1s
          annotations:
            summary: Appen har logget en error
            action: "https://logs.az.nav.no/goto/fbd44a2098fae956a0726c0c347a7632?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: critical

        - alert: rekrutteringsbistand-statistikk-api
          expr: sum(increase(log_messages_errors{app="rekrutteringsbistand-statistikk-api", level="Warning"}[10m])) > 3
          for: 1s
          annotations:
            summary: Økning i warnings
            action: "https://logs.az.nav.no/goto/fbd44a2098fae956a0726c0c347a7632?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: warning
