apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: rekrutteringsbistand-statistikk-api
  namespace: toi
  labels:
    team: toi
spec:
  image: {{version}}
  port: 8111
  ingresses:
      # TODO: Fjern arbeidsgiver.nais.preprod.local-ingress og context-path
    - https://arbeidsgiver.nais.preprod.local/rekrutteringsbistand-statistikk-api/
    - https://rekrutteringsbistand-statistikk-api.dev-fss-pub.nais.io
  liveness:
    path: /isalive
    initialDelay: 70
  readiness:
    path: /isready
    initialDelay: 70
  prometheus:
    enabled: true
    path: /rekrutteringsbistand-statistikk-api/metrics
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srv-rekbis-stat
        mountPath: /secret/serviceuser
  accessPolicy:
    inbound:
      rules:
        - application: rekrutteringsbistand-statistikk
          cluster: dev-gcp
        - application: rekrutteringsbistand-container
          cluster: dev-gcp
        - application: rekrutteringsbistand
          cluster: dev-gcp
        - application: rekrutteringsbistand-frontend
          cluster: dev-gcp
        - application: rekrutteringsbistand-kandidat-api
          cluster: dev-fss
  webproxy: true
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        extra:
          - NAVident
        groups:
          - id: "67a06857-0028-4a90-bf4c-9c9a92c7d733"   # adGruppeModiaGenerellTilgang
          - id: "0dba8374-bf36-4d89-bbba-662447d57b94"   # adGruppeJobbsøkerrettet
          - id: "52bc2af7-38d1-468b-b68d-0f3a4de45af2"   # adGruppeArbeidsgiverrettet
          - id: "a1749d9a-52e0-4116-bb9f-935c38f6c74a"   # adGruppeUtvikler
  env:
    - name: KAFKA_RAPID_TOPIC
      value: toi.rapid-1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: "rekrutteringsbistand-statistikk-api-rapidconsumer-5"
    #- name: KAFKA_EXTRA_TOPIC
    #  value: arbeidsgiver.tiltak-avtale-hendelse
    - name: KAFKA_RESET_POLICY
      value: "earliest"
    - name: HTTP_PORT
      value: "8111"
