apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: rekrutteringsbistand-statistikk-api
  namespace: toi
  labels:
    team: toi
spec:
  image: {{version}}
  port: 8111
  ingresses:
      # TODO: Fjern arbeidsgiver.nais.preprod.local-ingress og context-path
    - https://arbeidsgiver.nais.preprod.local/rekrutteringsbistand-statistikk-api/
    - https://rekrutteringsbistand-statistikk-api.dev-fss-pub.nais.io/rekrutteringsbistand-statistikk-api
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srv-rekbis-stat
        mountPath: /secret/serviceuser
  accessPolicy:
    inbound:
      rules:
        - application: rekrutteringsbistand-statistikk
          namespace: toi
          cluster: dev-gcp
        - application: rekrutteringsbistand-container
          namespace: toi
          cluster: dev-gcp
        - application: rekrutteringsbistand-kandidat-api
          namespace: toi
          cluster: dev-fss
  webproxy: true
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - NAVident
  env:
    - name: KAFKA_RAPID_TOPIC
      value: toi.rapid-1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: "rekrutteringsbistand-statistikk-api-rapidconsumer-4"
    - name: KAFKA_EXTRA_TOPIC
      value: arbeidsgiver.tiltak-avtale-hendelse
    - name: KAFKA_RESET_POLICY
      value: "earliest"
    - name: HTTP_PORT
      value: "8111"
