apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: rekrutteringsbistand-statistikk-api
  namespace: toi
  labels:
    team: toi
spec:
  image: {{version}}
  port: 8111
  ingresses:
      # TODO: Fjern arbeidsgiver.nais.preprod.local-ingress og context-path
    - https://arbeidsgiver.nais.preprod.local/rekrutteringsbistand-statistikk-api/
    - https://rekrutteringsbistand-statistikk-api.dev-fss-pub.nais.io/rekrutteringsbistand-statistikk-api
  #liveness:
  #  path: /rekrutteringsbistand-statistikk-api/internal/isAlive
  #readiness:
   # path: /rekrutteringsbistand-statistikk-api/internal/isReady
  #prometheus:
  #  enabled: true
  #  path: /rekrutteringsbistand-statistikk-api/internal/prometheus
  liveness:
    path: /rekrutteringsbistand-statistikk-api/isalive
  readiness:
    path: /rekrutteringsbistand-statistikk-api/isready
  prometheus:
    enabled: true
    path: /rekrutteringsbistand-statistikk-api/metrics
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srv-rekbis-stat
        mountPath: /secret/serviceuser
  accessPolicy:
    inbound:
      rules:
        - application: rekrutteringsbistand-statistikk
          namespace: toi
          cluster: dev-gcp
        - application: rekrutteringsbistand-container
          namespace: toi
          cluster: dev-gcp
        - application: rekrutteringsbistand-kandidat-api
          namespace: toi
          cluster: dev-fss
  webproxy: true
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      claims:
        extra:
          - NAVident
  env:
    - name: KAFKA_RAPID_TOPIC
      value: toi.rapid-1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: "rekrutteringsbistand-statistikk-api-rapidconsumer-1"
    - name: KAFKA_RESET_POLICY
      value: "latest"
