apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: rekrutteringsbistand-statistikk-api
  namespace: default
  labels:
    team: arbeidsgiver
spec:
  image: {{version}}
  ingresses:
    - https://arbeidsgiver.nais.preprod.local/rekrutteringsbistand-statistikk-api/
    - https://arbeidsgiver.dev.adeo.no/rekrutteringsbistand-statistikk-api/
  liveness:
    path: /rekrutteringsbistand-statistikk-api/internal/isAlive
  readiness:
    path: /rekrutteringsbistand-statistikk-api/internal/isReady
  prometheus:
    enabled: true
    path: /rekrutteringsbistand-statistikk-api/internal/prometheus
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srv-rekbis-stat
        mountPath: /secret/serviceuser
  webproxy: true
