apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: rekrutteringsbistand-statistikk-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{version}}
  port: 8111
  ingresses:
    - https://arbeidsgiver.nais.adeo.no/rekrutteringsbistand-statistikk-api/
    - https://rekrutteringsbistand-statistikk-api.prod-fss-pub.nais.io
  liveness:
    path: /rekrutteringsbistand-statistikk-api/internal/isAlive
  readiness:
    path: /rekrutteringsbistand-statistikk-api/internal/isReady
  prometheus:
    enabled: true
    path: /rekrutteringsbistand-statistikk-api/internal/prometheus
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srv-rekbis-stat
        mountPath: /secret/serviceuser
  accessPolicy:
    inbound:
      rules:
        - application: rekrutteringsbistand-statistikk
          namespace: toi
          cluster: prod-gcp
        - application: rekrutteringsbistand-container
          namespace: toi
          cluster: prod-gcp
        - application: rekrutteringsbistand-kandidat-api
          namespace: toi
          cluster: prod-fss
  webproxy: true
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
      claims:
        extra:
          - NAVident