apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: rekrutteringsbistand-statistikk-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{version}}
  port: 8111
  ingresses:
    - https://arbeidsgiver.nais.adeo.no/rekrutteringsbistand-statistikk-api/
    - https://rekrutteringsbistand-statistikk-api.prod-fss-pub.nais.io
  liveness:
    path: /rekrutteringsbistand-statistikk-api/internal/isAlive
  readiness:
    path: /rekrutteringsbistand-statistikk-api/internal/isReady
  prometheus:
    enabled: true
    path: /rekrutteringsbistand-statistikk-api/internal/prometheus
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srv-rekbis-stat
        mountPath: /secret/serviceuser
  webproxy: true
  azure:
    application:
      enabled: true
      claims:
        extra:
          - NAVident