apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: rekrutteringsbistand-statistikk-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{version}}
  port: 8111
  ingresses:
      # TODO: Fjern arbeidsgiver.nais.preprod.local-ingress og context-path
    - https://arbeidsgiver.nais.preprod.local/rekrutteringsbistand-statistikk-api/
    - https://rekrutteringsbistand-statistikk-api.dev-fss-pub.nais.io/rekrutteringsbistand-statistikk-api
  liveness:
    path: /rekrutteringsbistand-statistikk-api/internal/isAlive
  readiness:
    path: /rekrutteringsbistand-statistikk-api/internal/isReady
  prometheus:
    enabled: true
    path: /rekrutteringsbistand-statistikk-api/internal/prometheus
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srv-rekbis-stat
        mountPath: /secret/serviceuser
  accessPolicy:
    inbound:
      rules:
        - application: rekrutteringsbistand-statistikk
          namespace: toi
          cluster: dev-gcp
  webproxy: true
  azure:
    application:
      enabled: true
      claims:
        extra:
          - NAVident
