name: Deploy dvh-topic to prod

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/deploy-dvh-topic-to-prod.yaml
      - nais/dvh-topic-prod.yaml

jobs:
  deploy-kandidat-topic-to-prod:
    permissions:
      id-token: write
    name: Deploy dvh-topic to prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: nais/deploy/actions/deploy@849e900e3cfa7faf7ad1532bb3a3e6499c932199 # v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/dvh-topic-prod.yaml
